#include <iostream>
#include <algorithm>
#include <string>
#include <vector>
#include <queue>
#include <deque>
#include <stack>
#include <set>
using namespace std;

#define el "\n"
typedef long long ll;
typedef long double ld;
void solve()
{
  //  Q) https://codeforces.com/problemset/problem/1077/C  

    int t;
    cin >> t;

    while (t--) {
ll n, x, div=0,k;











          
    }
}


int main()
{
    ios::sync_with_stdio(false);
    cin.tie(NULL);

    solve();

    return 0;
}

